service: notetaker-server
plugins:
  - serverless-dotenv-plugin
provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2
  memorySize: 128
functions:
  notetaker:
    handler: index.handler
    environment: 
      MONGODB_URI: ${env:MONGODB_URI}
      MONGODB_NAME: ${env:MONGODB_NAME}
      API_BASE_URL: ${env:API_BASE_URL}
      API_PORT: ${env:API_PORT}
      CORS_ORIGIN: ${env:CORS_ORIGIN}
      LOG_LEVEL: ${env:LOG_LEVEL}
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true